version: '3.9'

services:
  alfred:
    extends:
      file: common.yml
      service: common
    container_name: alfred
    image: alfred:latest
    build:
      context: ${COMPOSE_BASE_DIRECTORY}/Alfred
      dockerfile: ./docker/Dockerfile.dev
      args:
        HTTP_PORT: ${HTTP_PORT}
        RPC_PORT: ${RPC_PORT}
    volumes:
      - ${COMPOSE_BASE_DIRECTORY}/Alfred:/app
    depends_on:
      - gateway
      - mongo
    labels:
      - traefik.enable=true

      - traefik.http.routers.alfred_rpc.entrypoints=rpc
      - traefik.http.routers.alfred_rpc.rule=PathPrefix(`/turnly.alfred.v1`) && Host(`rpc.turnly`) || Host(`host.docker.internal`)
      - traefik.http.routers.alfred_rpc.service=alfred_rpc
      - traefik.http.services.alfred_rpc.loadbalancer.server.port=${RPC_PORT}
      - traefik.http.services.alfred_rpc.loadbalancer.server.scheme=h2c

      - traefik.http.routers.alfred_http.entrypoints=http
      - traefik.http.routers.alfred_http.rule=Host(`api.turnly`) && PathPrefix(`/v1/fields`, `/v1/answers`)
      - traefik.http.routers.alfred_http.service=alfred_http
      - traefik.http.services.alfred_http.loadbalancer.server.port=${HTTP_PORT}
