version: '3.9'

services:
  bifrost:
    extends:
      file: common.yml
      service: common
    container_name: bifrost.api
    image: bifrost:latest
    build:
      context: ${DOCKER_RELATIVE_APPS_DIR}/Bifrost.API
      dockerfile: ./docker/Dockerfile.dev
      args:
        HTTP_PORT: ${HTTP_PORT}
    volumes:
      - ${DOCKER_RELATIVE_APPS_DIR}/Bifrost.API:/app
    depends_on:
      - gateway
    labels:
      - traefik.enable=true

      - traefik.http.routers.bifrost_http.entrypoints=http
      - traefik.http.routers.bifrost_http.rule=Host(`stream.turnly`)
      - traefik.http.routers.bifrost_http.service=bifrost_http
      - traefik.http.services.bifrost_http.loadbalancer.server.port=${HTTP_PORT}
