version: '3.9'

services:
  realtime-api:
    extends:
      file: common.yml
      service: common
    container_name: realtime-api
    image: realtime-api:latest
    build:
      context: ${DOCKER_RELATIVE_APPS_DIR}/realtime-api
      dockerfile: ./docker/Dockerfile.dev
      args:
        HTTP_PORT: ${HTTP_PORT}
    volumes:
      - ${DOCKER_RELATIVE_APPS_DIR}/realtime-api:/app
    depends_on:
      - gateway
    labels:
      - traefik.enable=true

      - traefik.http.routers.realtime-api-http.entrypoints=http
      - traefik.http.routers.realtime-api-http.rule=Host(`realtime.turnly`)
      - traefik.http.routers.realtime-api-http.service=realtime-api-http
      - traefik.http.services.realtime-api-http.loadbalancer.server.port=${HTTP_PORT}
