maverick:
  - apps/Maverick/**/*
heimdall:
  - apps/Heimdall/**/*
wayne:
  - apps/Wayne/**/*
alfred:
  - apps/Alfred/**/*
shannon:
  - apps/Shannon/**/*
dorothee:
  - apps/Dorothee/**/*
queuing-system:
  - apps/queuing-system/**/*
curry:
  - apps/Curry/**/*
chanel:
  - apps/Chanel/**/*
brennan:
  - apps/Brennan/**/*
polly:
  - apps/Polly/**/*
bifrost:
  - apps/Bifrost.API/**/*
docker:
  - apps/**/docker/*
operator:
  - devo/scripts/**/*
devo:
  - devo/**/*
documentation:
  - docs/**/*
environment:
  - .env.example
