addons:
  - apps/addons/**/*
heimdall:
  - apps/heimdall/**/*
billing:
  - apps/billing/**/*
assistance-centers:
  - apps/assistance-centers/**/*
team:
  - apps/team/**/*
custom-fields:
  - apps/custom-fields/**/*
queuing-system:
  - apps/queuing-system/**/*
tasks-scheduling:
  - apps/tasks-scheduling/**/*
notifications:
  - apps/notifications/**/*
business-owners:
  - apps/business-owners/**/*
interactions:
  - apps/interactions/**/*
streaming-api:
  - apps/streaming-api/**/*
docker:
  - apps/**/docker/*
operator:
  - devo/scripts/**/*
devo:
  - devo/**/*
documentation:
  - docs/**/*
environment:
  - .env.example
