moss:
  - apps/moss/**/*
heimdall:
  - apps/heimdall/**/*
wayne:
  - apps/wayne/**/*
alfred:
  - apps/alfred/**/*
shannon:
  - apps/shannon/**/*
dorothee:
  - apps/dorothee/**/*
shelby:
  - apps/shelby/**/*
curry:
  - apps/curry/**/*
chanel:
  - apps/chanel/**/*
brennan:
  - apps/brennan/**/*
polly:
  - apps/polly/**/*
docker:
  - apps/**/docker/*
operator:
  - compose/**/*
  - scripts/**/*
documentation:
  - docs/**/*
environment:
  - .env.example
