maverick:
  - apps/Maverick/**/*
heimdall:
  - apps/heimdall/**/*
wayne:
  - apps/Wayne/**/*
assistance-centers:
  - apps/assistance-centers/**/*
shannon:
  - apps/Shannon/**/*
dorothee:
  - apps/Dorothee/**/*
queuing-system:
  - apps/queuing-system/**/*
curry:
  - apps/Curry/**/*
chanel:
  - apps/Chanel/**/*
brennan:
  - apps/Brennan/**/*
polly:
  - apps/Polly/**/*
streaming-api:
  - apps/streaming-api/**/*
docker:
  - apps/**/docker/*
operator:
  - devo/scripts/**/*
devo:
  - devo/**/*
documentation:
  - docs/**/*
environment:
  - .env.example
