version: '3.9'

services:
  rabbitmq:
    extends:
      file: common.yml
      service: common
    image: rabbitmq:3.10.5-management-alpine
    container_name: rabbitmq
    tty: true
    stdin_open: true
    ports:
      # HTTP DASHBOARD FOR MANAGEMENT
      - ${RABBITMQ_UI_PORT}:15672
      # AMQP PROTOCOL
      - 5672:5672
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq/mnesia/

volumes:
  rabbitmq_data:
