version: '3.9'

services:
  mongo:
    extends:
      file: common.yml
      service: common
    image: mongo:5.0.12
    container_name: mongo
    environment:
      NODE_ENV: ${NODE_ENV}
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    ports:
      - ${MONGO_PORT}:27017
    volumes:
      - mongo_data:/data/db
      - ./infrastructure/datasources/mongo/:/docker-entrypoint-initdb.d/:ro

volumes:
  mongo_data:
