version: '3.9'

services:
  redis:
    extends:
      file: common.yml
      service: common
    image: redis
    hostname: redis
    container_name: redis
    volumes:
      - redis_data:/data
    ports:
      - ${REDIS_PORT}:6379

volumes:
  redis_data:
