accesslog: true

log:
  level: DEBUG

api:
  insecure: true
  dashboard: true
  debug: true

entryPoints:
  web:
    address: :80
  websecure:
    address: :443

providers:
  docker:
    exposedbydefault: false
    watch: true
