version: '3.9'

services:
  mongo:
    extends:
      file: common.yml
      service: common
    image: mongo
    container_name: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    ports:
      - ${MONGO_PORT}:27017
    volumes:
      - mongo_data:/data/db
      - ./infrastructure/datasources/mongo/:/docker-entrypoint-initdb.d/:ro

  mongo_ui:
    extends:
      file: common.yml
      service: common
    container_name: mongo_ui
    image: mongo-express
    ports:
      - ${MONGO_UI_PORT}:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_USERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_PASSWORD}
      ME_CONFIG_MONGODB_URL: mongodb://${MONGO_USERNAME}:${MONGO_PASSWORD}@mongo:${MONGO_PORT}/

volumes:
  mongo_data:
