version: '3.9'

services:
  mongo:
    extends:
      file: common.yml
      service: common
    image: mongo
    container_name: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: turnly
    ports:
      - ${MONGO_PORT}:27017
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
