version: '3.9'

services:
  gateway:
    extends:
      file: common.yml
      service: common
    image: gateway:latest
    container_name: gateway
    build:
      context: ${COMPOSE_BASE_DIRECTORY}/Gateway
      dockerfile: ./docker/Dockerfile
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    ports:
      - ${APP_PROXY_DASHBOARD_PORT}:8080
      - ${HTTP_PORT}:${HTTP_PORT}
      - ${RPC_PORT}:${RPC_PORT}
    networks:
      turnly:
        aliases:
          - ${APP_PROXY_HOST}

networks:
  turnly:
