name: 🔋 CI - Test Suites

on:
  pull_request:
    paths:
      - apps/**
    branches:
      - develop
      - main

  push:
    paths:
      - apps/**
    branches:
      - develop
      - main

env:
  MONGO_DB: turnly_testing_db
  MONGO_USERNAME: root
  MONGO_PASSWORD: turnly

jobs:
  unit_and_integration:
    name: 🧩 Unit & Integration
    uses: ./.github/workflows/unit-and-integration-tests.yml
    with:
      mongo-username: ${{ env.MONGO_USERNAME }}
      mongo-password: ${{ env.MONGO_PASSWORD }}
      mongo-db: ${{ env.MONGO_DB }}

  e2e_and_benchmark:
    name: 🧩 E2E & Benchmark
    uses: ./.github/workflows/e2e-and-benchmark-tests.yml
    with:
      mongo-username: ${{ env.MONGO_USERNAME }}
      mongo-password: ${{ env.MONGO_PASSWORD }}
      mongo-db: ${{ env.MONGO_DB }}
