name: 🏷️ Pull Request Labels

on:
  pull_request_target:
    branches:
      - main
      - develop

jobs:
  triage:
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
    - uses: actions/labeler@v4
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
